/*
 Jose Galán Simó
 2 - DAM
 */
package View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author god
 */
public class InputFamilia extends javax.swing.JDialog {

    public void messageERROR(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "INFO",
                JOptionPane.ERROR_MESSAGE);
    }

    public void messageINFO(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "INFO",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Creates new form InputFamilia
     */
    public InputFamilia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private boolean isAdd;

    public boolean isIsAdd() {
        return isAdd;
    }

    public void setIsAdd(boolean isAdd) {
        this.isAdd = isAdd;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlabelTitle = new javax.swing.JLabel();
        PanelCenter = new javax.swing.JPanel();
        PanelFamilia = new javax.swing.JPanel();
        jLabelx1 = new javax.swing.JLabel();
        jTextFieldFamilia = new javax.swing.JTextField();
        PanelImagen = new javax.swing.JPanel();
        jLabelx2 = new javax.swing.JLabel();
        jTextFieldFoto = new javax.swing.JTextField();
        PanelEsMenu = new javax.swing.JPanel();
        jLabelx3 = new javax.swing.JLabel();
        jComboBoxEsMenu = new javax.swing.JComboBox<String>();
        PanelVer = new javax.swing.JPanel();
        jLabelx4 = new javax.swing.JLabel();
        jTextFieldVer = new javax.swing.JTextField();
        PanelSouth = new javax.swing.JPanel();
        jBUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1, 45));

        jlabelTitle.setBackground(new java.awt.Color(204, 255, 255));
        jlabelTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelTitle.setText("Insertar Familia");
        jlabelTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlabelTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jlabelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlabelTitle.setMaximumSize(new java.awt.Dimension(250, 30));
        jlabelTitle.setMinimumSize(new java.awt.Dimension(250, 30));
        jlabelTitle.setPreferredSize(new java.awt.Dimension(250, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jlabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jlabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MainPanel.add(jPanel1, java.awt.BorderLayout.NORTH);

        PanelCenter.setLayout(new java.awt.GridLayout(4, 1));

        PanelFamilia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelFamilia.setLayout(new java.awt.GridBagLayout());

        jLabelx1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx1.setText("Familia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        PanelFamilia.add(jLabelx1, gridBagConstraints);

        jTextFieldFamilia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldFamilia.setMinimumSize(new java.awt.Dimension(150, 30));
        jTextFieldFamilia.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        PanelFamilia.add(jTextFieldFamilia, gridBagConstraints);

        PanelCenter.add(PanelFamilia);

        PanelImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelImagen.setLayout(new java.awt.GridBagLayout());

        jLabelx2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx2.setText("Foto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        PanelImagen.add(jLabelx2, gridBagConstraints);

        jTextFieldFoto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldFoto.setMinimumSize(new java.awt.Dimension(150, 30));
        jTextFieldFoto.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        PanelImagen.add(jTextFieldFoto, gridBagConstraints);

        PanelCenter.add(PanelImagen);

        PanelEsMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelEsMenu.setLayout(new java.awt.GridBagLayout());

        jLabelx3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx3.setText("EsMenu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        PanelEsMenu.add(jLabelx3, gridBagConstraints);

        jComboBoxEsMenu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jComboBoxEsMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));
        jComboBoxEsMenu.setMinimumSize(new java.awt.Dimension(100, 35));
        jComboBoxEsMenu.setPreferredSize(new java.awt.Dimension(100, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        PanelEsMenu.add(jComboBoxEsMenu, gridBagConstraints);

        PanelCenter.add(PanelEsMenu);

        PanelVer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelVer.setLayout(new java.awt.GridBagLayout());

        jLabelx4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx4.setText("Ver");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        PanelVer.add(jLabelx4, gridBagConstraints);

        jTextFieldVer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldVer.setMinimumSize(new java.awt.Dimension(150, 30));
        jTextFieldVer.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        PanelVer.add(jTextFieldVer, gridBagConstraints);

        PanelCenter.add(PanelVer);

        MainPanel.add(PanelCenter, java.awt.BorderLayout.CENTER);

        PanelSouth.setBackground(new java.awt.Color(255, 255, 255));

        jBUTTON.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBUTTON.setText("Insertar");
        jBUTTON.setMaximumSize(new java.awt.Dimension(80, 30));
        jBUTTON.setMinimumSize(new java.awt.Dimension(80, 30));
        jBUTTON.setPreferredSize(new java.awt.Dimension(180, 50));
        PanelSouth.add(jBUTTON);

        MainPanel.add(PanelSouth, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void editarVentana(String str) {
        this.setTitle(str + " Familia");
        this.jlabelTitle.setText(str + " Familia");
        this.jBUTTON.setText(str);
    }

    public JButton getjBUTTON() {
        return jBUTTON;
    }

    public JComboBox<String> getjComboBoxEsMenu() {
        return jComboBoxEsMenu;
    }

    public JTextField getjTextFieldFamilia() {
        return jTextFieldFamilia;
    }

    public JTextField getjTextFieldFoto() {
        return jTextFieldFoto;
    }

    public JTextField getjTextFieldVer() {
        return jTextFieldVer;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputFamilia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InputFamilia dialog = new InputFamilia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel PanelEsMenu;
    private javax.swing.JPanel PanelFamilia;
    private javax.swing.JPanel PanelImagen;
    private javax.swing.JPanel PanelSouth;
    private javax.swing.JPanel PanelVer;
    private javax.swing.JButton jBUTTON;
    private javax.swing.JComboBox<String> jComboBoxEsMenu;
    private javax.swing.JLabel jLabelx1;
    private javax.swing.JLabel jLabelx2;
    private javax.swing.JLabel jLabelx3;
    private javax.swing.JLabel jLabelx4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldFamilia;
    private javax.swing.JTextField jTextFieldFoto;
    private javax.swing.JTextField jTextFieldVer;
    private javax.swing.JLabel jlabelTitle;
    // End of variables declaration//GEN-END:variables
}
