/*
 Jose Galán Simó
 2 - DAM
 */
package View;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author god
 */
public class ProductoView extends javax.swing.JFrame {

    public JButton getjButtonAdd() {
        return jButtonAdd;
    }

    public JButton getjButtonDelete() {
        return jButtonDelete;
    }

    public JButton getjButtonEdit() {
        return jButtonEdit;
    }

    /**
     * Creates new form ProductoView
     */
    public ProductoView() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public void setFamilia(String s) {
        this.jLabel_familia_.setText("Familia: " + s);
    }

    public JButton getjButtonSearch() {
        return jButtonSearch;
    }

    public void messageERROR(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "INFO",
                JOptionPane.ERROR_MESSAGE);
    }

    public void messageINFO(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "INFO",
                JOptionPane.INFORMATION_MESSAGE);
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JTextField getjTextFieldSearch() {
        return jTextFieldSearch;
    }

    public JButton getjButtonVolver() {
        return jButtonVolver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelSouth = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        PanelCenter = new javax.swing.JPanel();
        PanelCenter_Main = new javax.swing.JPanel();
        Panel_buttonEAST2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Panel_buttonWEST = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Panel_buttonEAST = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelData = new javax.swing.JPanel();
        PanelDataLeft = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Panel_buttonEAST1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelFirst = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_familia_ = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Productos");

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainPanel.setLayout(new java.awt.BorderLayout());

        PanelTitle.setBackground(new java.awt.Color(255, 255, 255));
        PanelTitle.setPreferredSize(new java.awt.Dimension(1, 45));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Productos");
        PanelTitle.add(jLabel1);

        MainPanel.add(PanelTitle, java.awt.BorderLayout.NORTH);

        PanelSouth.setBackground(new java.awt.Color(255, 255, 255));

        jButtonAdd.setText("Añadir");
        PanelSouth.add(jButtonAdd);

        jButtonDelete.setText("Eliminar");
        jButtonDelete.setEnabled(false);
        PanelSouth.add(jButtonDelete);

        jButtonEdit.setText("Editar");
        jButtonEdit.setEnabled(false);
        PanelSouth.add(jButtonEdit);

        MainPanel.add(PanelSouth, java.awt.BorderLayout.SOUTH);

        PanelCenter.setLayout(new java.awt.BorderLayout());

        PanelCenter_Main.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelCenter_Main.setLayout(new java.awt.BorderLayout());

        Panel_buttonEAST2.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("   ");
        Panel_buttonEAST2.add(jLabel7, new java.awt.GridBagConstraints());

        PanelCenter_Main.add(Panel_buttonEAST2, java.awt.BorderLayout.SOUTH);

        Panel_buttonWEST.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("   ");
        Panel_buttonWEST.add(jLabel5, new java.awt.GridBagConstraints());

        PanelCenter_Main.add(Panel_buttonWEST, java.awt.BorderLayout.WEST);

        Panel_buttonEAST.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("   ");
        Panel_buttonEAST.add(jLabel4, new java.awt.GridBagConstraints());

        PanelCenter_Main.add(Panel_buttonEAST, java.awt.BorderLayout.EAST);

        PanelData.setLayout(new java.awt.GridLayout(1, 0));

        PanelDataLeft.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Foto", "ver", "PVP", "Coste", "DeCocina", "EsMenu", "EsPlantilla"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(50);
        }

        PanelDataLeft.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PanelData.add(PanelDataLeft);

        PanelCenter_Main.add(PanelData, java.awt.BorderLayout.CENTER);

        Panel_buttonEAST1.setLayout(new java.awt.GridBagLayout());

        jLabel6.setText("   ");
        Panel_buttonEAST1.add(jLabel6, new java.awt.GridBagConstraints());

        PanelCenter_Main.add(Panel_buttonEAST1, java.awt.BorderLayout.NORTH);

        PanelCenter.add(PanelCenter_Main, java.awt.BorderLayout.CENTER);

        PanelFirst.setLayout(new javax.swing.BoxLayout(PanelFirst, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVolver.setText("Volver");
        jPanel1.add(jButtonVolver);

        PanelFirst.add(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 10));

        jLabel_familia_.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_familia_.setText("_familia_");
        jPanel2.add(jLabel_familia_);

        PanelFirst.add(jPanel2);

        jPanel5.setPreferredSize(new java.awt.Dimension(80, 33));

        jTextFieldSearch.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextFieldSearch.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel5.add(jTextFieldSearch);

        jButtonSearch.setText("Buscar");
        jPanel5.add(jButtonSearch);

        PanelFirst.add(jPanel5);

        PanelCenter.add(PanelFirst, java.awt.BorderLayout.NORTH);

        MainPanel.add(PanelCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel PanelCenter_Main;
    private javax.swing.JPanel PanelData;
    private javax.swing.JPanel PanelDataLeft;
    private javax.swing.JPanel PanelFirst;
    private javax.swing.JPanel PanelSouth;
    private javax.swing.JPanel PanelTitle;
    private javax.swing.JPanel Panel_buttonEAST;
    private javax.swing.JPanel Panel_buttonEAST1;
    private javax.swing.JPanel Panel_buttonEAST2;
    private javax.swing.JPanel Panel_buttonWEST;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_familia_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
