package View;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author lliurex
 */
public class ComprasView extends javax.swing.JFrame {

    /**
     * Creates new form ComprasView
     */
    public ComprasView() {
        try {
            this.setIconImage(new ImageIcon(System.getProperty("user.dir") + "\\src\\images\\compras.png").getImage());
        } catch (Exception e) {
        }
        initComponents();
        setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public JButton getxBotonVOLVER() {
        return xBotonVOLVER;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelSouth = new javax.swing.JPanel();
        xBotonAdd = new javax.swing.JButton();
        xBotonDelete = new javax.swing.JButton();
        xBotonEdit = new javax.swing.JButton();
        PanelCenter = new javax.swing.JPanel();
        PanelCenter_Main = new javax.swing.JPanel();
        Panel_buttonEAST2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Panel_buttonWEST = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Panel_buttonEAST = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelData = new javax.swing.JPanel();
        PanelDataLeft = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTABLA = new javax.swing.JTable();
        Panel_buttonEAST1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelFirst = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        xBotonVOLVER = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        xTextFieldBUSCAR = new javax.swing.JTextField();
        xBotonSEARCH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compras");
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainPanel.setLayout(new java.awt.BorderLayout());

        PanelTitle.setBackground(new java.awt.Color(255, 255, 255));
        PanelTitle.setPreferredSize(new java.awt.Dimension(1, 45));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compras.png"))); // NOI18N
        jLabel1.setText("Compras");
        PanelTitle.add(jLabel1);

        MainPanel.add(PanelTitle, java.awt.BorderLayout.NORTH);

        PanelSouth.setBackground(new java.awt.Color(255, 255, 255));

        xBotonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        xBotonAdd.setText("Añadir");
        PanelSouth.add(xBotonAdd);

        xBotonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        xBotonDelete.setText("Eliminar");
        xBotonDelete.setEnabled(false);
        PanelSouth.add(xBotonDelete);

        xBotonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        xBotonEdit.setText("Editar");
        xBotonEdit.setEnabled(false);
        PanelSouth.add(xBotonEdit);

        MainPanel.add(PanelSouth, java.awt.BorderLayout.SOUTH);

        PanelCenter.setLayout(new java.awt.BorderLayout());

        PanelCenter_Main.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelCenter_Main.setLayout(new java.awt.BorderLayout());

        Panel_buttonEAST2.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("   ");
        Panel_buttonEAST2.add(jLabel7, new java.awt.GridBagConstraints());

        PanelCenter_Main.add(Panel_buttonEAST2, java.awt.BorderLayout.SOUTH);

        Panel_buttonWEST.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("   ");
        Panel_buttonWEST.add(jLabel5, new java.awt.GridBagConstraints());

        PanelCenter_Main.add(Panel_buttonWEST, java.awt.BorderLayout.WEST);

        Panel_buttonEAST.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("   ");
        Panel_buttonEAST.add(jLabel4, new java.awt.GridBagConstraints());

        PanelCenter_Main.add(Panel_buttonEAST, java.awt.BorderLayout.EAST);

        PanelData.setLayout(new java.awt.GridLayout(1, 0));

        PanelDataLeft.setLayout(new java.awt.BorderLayout());

        xTABLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Fecha", "Proveedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(xTABLA);
        if (xTABLA.getColumnModel().getColumnCount() > 0) {
            xTABLA.getColumnModel().getColumn(0).setPreferredWidth(100);
            xTABLA.getColumnModel().getColumn(1).setResizable(false);
            xTABLA.getColumnModel().getColumn(1).setPreferredWidth(40);
            xTABLA.getColumnModel().getColumn(2).setResizable(false);
            xTABLA.getColumnModel().getColumn(2).setPreferredWidth(8);
        }

        PanelDataLeft.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PanelData.add(PanelDataLeft);

        PanelCenter_Main.add(PanelData, java.awt.BorderLayout.CENTER);

        Panel_buttonEAST1.setLayout(new java.awt.GridBagLayout());

        jLabel6.setText("   ");
        Panel_buttonEAST1.add(jLabel6, new java.awt.GridBagConstraints());

        PanelCenter_Main.add(Panel_buttonEAST1, java.awt.BorderLayout.NORTH);

        PanelCenter.add(PanelCenter_Main, java.awt.BorderLayout.CENTER);

        PanelFirst.setLayout(new javax.swing.BoxLayout(PanelFirst, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

        xBotonVOLVER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        xBotonVOLVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        xBotonVOLVER.setText("Volver");
        jPanel1.add(xBotonVOLVER);

        PanelFirst.add(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 10));
        PanelFirst.add(jPanel2);

        jPanel5.setPreferredSize(new java.awt.Dimension(120, 33));

        xTextFieldBUSCAR.setMinimumSize(new java.awt.Dimension(150, 20));
        xTextFieldBUSCAR.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel5.add(xTextFieldBUSCAR);

        xBotonSEARCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        xBotonSEARCH.setText("Buscar por Producto");
        jPanel5.add(xBotonSEARCH);

        PanelFirst.add(jPanel5);

        PanelCenter.add(PanelFirst, java.awt.BorderLayout.NORTH);

        MainPanel.add(PanelCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getxBotonAdd() {
        return xBotonAdd;
    }

    public JButton getxBotonDelete() {
        return xBotonDelete;
    }

    public JButton getxBotonEdit() {
        return xBotonEdit;
    }

    public JButton getxBotonSEARCH() {
        return xBotonSEARCH;
    }

    public JTable getxTABLA() {
        return xTABLA;
    }

    public JTextField getxTextFieldBUSCAR() {
        return xTextFieldBUSCAR;
    }

    public void showError(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
    }

    public void showInfo(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "INFO",
                JOptionPane.INFORMATION_MESSAGE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel PanelCenter_Main;
    private javax.swing.JPanel PanelData;
    private javax.swing.JPanel PanelDataLeft;
    private javax.swing.JPanel PanelFirst;
    private javax.swing.JPanel PanelSouth;
    private javax.swing.JPanel PanelTitle;
    private javax.swing.JPanel Panel_buttonEAST;
    private javax.swing.JPanel Panel_buttonEAST1;
    private javax.swing.JPanel Panel_buttonEAST2;
    private javax.swing.JPanel Panel_buttonWEST;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton xBotonAdd;
    private javax.swing.JButton xBotonDelete;
    private javax.swing.JButton xBotonEdit;
    private javax.swing.JButton xBotonSEARCH;
    private javax.swing.JButton xBotonVOLVER;
    private javax.swing.JTable xTABLA;
    private javax.swing.JTextField xTextFieldBUSCAR;
    // End of variables declaration//GEN-END:variables
}
