package View;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author lliurex
 */
public class InputCompraView extends javax.swing.JDialog {

    /**
     * Creates new form InputCompraView
     */
    public InputCompraView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void editarVentana(String s) {
        this.setTitle(s+" Compra");
        this.xLabelTITULO.setText(s+" Compra");
        this.xBotonACEPTAR.setText(s);
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        xLabelTITULO = new javax.swing.JLabel();
        PanelCenter = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jLabelx3 = new javax.swing.JLabel();
        xComboBoxPRODUCTO = new javax.swing.JComboBox<>();
        panel2 = new javax.swing.JPanel();
        jLabelx2 = new javax.swing.JLabel();
        xTextFieldCANTIDAD = new javax.swing.JTextField();
        panel3 = new javax.swing.JPanel();
        jLabelx5 = new javax.swing.JLabel();
        xComboBoxPROVEEDOR = new javax.swing.JComboBox<>();
        PanelSouth = new javax.swing.JPanel();
        xBotonACEPTAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Compra");
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1, 45));

        xLabelTITULO.setBackground(new java.awt.Color(204, 255, 255));
        xLabelTITULO.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        xLabelTITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabelTITULO.setText("Compra");
        xLabelTITULO.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabelTITULO.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        xLabelTITULO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xLabelTITULO.setMaximumSize(new java.awt.Dimension(250, 30));
        xLabelTITULO.setMinimumSize(new java.awt.Dimension(250, 30));
        xLabelTITULO.setPreferredSize(new java.awt.Dimension(250, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(xLabelTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(xLabelTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MainPanel.add(jPanel1, java.awt.BorderLayout.NORTH);

        PanelCenter.setLayout(new java.awt.GridLayout(3, 1));

        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1.setLayout(new java.awt.GridBagLayout());

        jLabelx3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx3.setText("Producto:   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        panel1.add(jLabelx3, gridBagConstraints);

        xComboBoxPRODUCTO.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xComboBoxPRODUCTO.setMinimumSize(new java.awt.Dimension(150, 35));
        xComboBoxPRODUCTO.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel1.add(xComboBoxPRODUCTO, gridBagConstraints);

        PanelCenter.add(panel1);

        panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel2.setLayout(new java.awt.GridBagLayout());

        jLabelx2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx2.setText("Cantidad:   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        panel2.add(jLabelx2, gridBagConstraints);

        xTextFieldCANTIDAD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xTextFieldCANTIDAD.setMinimumSize(new java.awt.Dimension(150, 30));
        xTextFieldCANTIDAD.setPreferredSize(new java.awt.Dimension(180, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel2.add(xTextFieldCANTIDAD, gridBagConstraints);

        PanelCenter.add(panel2);

        panel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel3.setLayout(new java.awt.GridBagLayout());

        jLabelx5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx5.setText("Proveedor: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        panel3.add(jLabelx5, gridBagConstraints);

        xComboBoxPROVEEDOR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xComboBoxPROVEEDOR.setMinimumSize(new java.awt.Dimension(150, 35));
        xComboBoxPROVEEDOR.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel3.add(xComboBoxPROVEEDOR, gridBagConstraints);

        PanelCenter.add(panel3);

        MainPanel.add(PanelCenter, java.awt.BorderLayout.CENTER);

        PanelSouth.setBackground(new java.awt.Color(255, 255, 255));

        xBotonACEPTAR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xBotonACEPTAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok.png"))); // NOI18N
        xBotonACEPTAR.setText("Aceptar");
        xBotonACEPTAR.setMaximumSize(new java.awt.Dimension(80, 30));
        xBotonACEPTAR.setMinimumSize(new java.awt.Dimension(80, 30));
        xBotonACEPTAR.setPreferredSize(new java.awt.Dimension(180, 50));
        PanelSouth.add(xBotonACEPTAR);

        MainPanel.add(PanelSouth, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getxBotonACEPTAR() {
        return xBotonACEPTAR;
    }

    public JComboBox<String> getxComboBoxPRODUCTO() {
        return xComboBoxPRODUCTO;
    }

    public JComboBox<String> getxComboBoxPROVEEDOR() {
        return xComboBoxPROVEEDOR;
    }

    public JLabel getxLabelTITULO() {
        return xLabelTITULO;
    }

    public JTextField getxTextFieldCANTIDAD() {
        return xTextFieldCANTIDAD;
    }

    public void showError(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
    }

    public void showInfo(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "INFO",
                JOptionPane.INFORMATION_MESSAGE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel PanelSouth;
    private javax.swing.JLabel jLabelx2;
    private javax.swing.JLabel jLabelx3;
    private javax.swing.JLabel jLabelx5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JButton xBotonACEPTAR;
    private javax.swing.JComboBox<String> xComboBoxPRODUCTO;
    private javax.swing.JComboBox<String> xComboBoxPROVEEDOR;
    private javax.swing.JLabel xLabelTITULO;
    private javax.swing.JTextField xTextFieldCANTIDAD;
    // End of variables declaration//GEN-END:variables
}
