/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author god
 */
public class InputProveedorView extends javax.swing.JDialog {

    /**
     * Creates new form InputProveedorView
     */
    public InputProveedorView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        xLabelTITULO = new javax.swing.JLabel();
        PanelCenter = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jLabelx3 = new javax.swing.JLabel();
        xTextFieldNOMBRE = new javax.swing.JTextField();
        panel2 = new javax.swing.JPanel();
        jLabelx2 = new javax.swing.JLabel();
        xTextFieldDIR = new javax.swing.JTextField();
        panel3 = new javax.swing.JPanel();
        jLabelx5 = new javax.swing.JLabel();
        xTextFieldPOB = new javax.swing.JTextField();
        panel4 = new javax.swing.JPanel();
        jLabelx6 = new javax.swing.JLabel();
        xTextFieldCP = new javax.swing.JTextField();
        panel5 = new javax.swing.JPanel();
        jLabelx7 = new javax.swing.JLabel();
        xTextFieldCIF = new javax.swing.JTextField();
        panel6 = new javax.swing.JPanel();
        jLabelx8 = new javax.swing.JLabel();
        xTextFieldPROV = new javax.swing.JTextField();
        panel7 = new javax.swing.JPanel();
        jLabelx9 = new javax.swing.JLabel();
        xTextFieldTEL = new javax.swing.JTextField();
        PanelSouth = new javax.swing.JPanel();
        xBotonACEPTAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proveedor");
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1, 45));

        xLabelTITULO.setBackground(new java.awt.Color(204, 255, 255));
        xLabelTITULO.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        xLabelTITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabelTITULO.setText("Proveedor");
        xLabelTITULO.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabelTITULO.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        xLabelTITULO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xLabelTITULO.setMaximumSize(new java.awt.Dimension(250, 30));
        xLabelTITULO.setMinimumSize(new java.awt.Dimension(250, 30));
        xLabelTITULO.setPreferredSize(new java.awt.Dimension(250, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(xLabelTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(xLabelTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MainPanel.add(jPanel1, java.awt.BorderLayout.NORTH);

        PanelCenter.setLayout(new java.awt.GridLayout(7, 1));

        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1.setLayout(new java.awt.GridBagLayout());

        jLabelx3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx3.setText("Nombre:   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        panel1.add(jLabelx3, gridBagConstraints);

        xTextFieldNOMBRE.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xTextFieldNOMBRE.setMinimumSize(new java.awt.Dimension(150, 30));
        xTextFieldNOMBRE.setPreferredSize(new java.awt.Dimension(180, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel1.add(xTextFieldNOMBRE, gridBagConstraints);

        PanelCenter.add(panel1);

        panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel2.setLayout(new java.awt.GridBagLayout());

        jLabelx2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx2.setText("Dirección:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        panel2.add(jLabelx2, gridBagConstraints);

        xTextFieldDIR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xTextFieldDIR.setMinimumSize(new java.awt.Dimension(150, 30));
        xTextFieldDIR.setPreferredSize(new java.awt.Dimension(180, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel2.add(xTextFieldDIR, gridBagConstraints);

        PanelCenter.add(panel2);

        panel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel3.setLayout(new java.awt.GridBagLayout());

        jLabelx5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx5.setText("Población:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        panel3.add(jLabelx5, gridBagConstraints);

        xTextFieldPOB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xTextFieldPOB.setMinimumSize(new java.awt.Dimension(150, 30));
        xTextFieldPOB.setPreferredSize(new java.awt.Dimension(180, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel3.add(xTextFieldPOB, gridBagConstraints);

        PanelCenter.add(panel3);

        panel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel4.setLayout(new java.awt.GridBagLayout());

        jLabelx6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx6.setText("Codigo postal: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        panel4.add(jLabelx6, gridBagConstraints);

        xTextFieldCP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xTextFieldCP.setMinimumSize(new java.awt.Dimension(150, 30));
        xTextFieldCP.setPreferredSize(new java.awt.Dimension(180, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel4.add(xTextFieldCP, gridBagConstraints);

        PanelCenter.add(panel4);

        panel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel5.setLayout(new java.awt.GridBagLayout());

        jLabelx7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx7.setText("CIF:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        panel5.add(jLabelx7, gridBagConstraints);

        xTextFieldCIF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xTextFieldCIF.setMinimumSize(new java.awt.Dimension(150, 30));
        xTextFieldCIF.setPreferredSize(new java.awt.Dimension(180, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel5.add(xTextFieldCIF, gridBagConstraints);

        PanelCenter.add(panel5);

        panel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel6.setLayout(new java.awt.GridBagLayout());

        jLabelx8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx8.setText("Provincia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        panel6.add(jLabelx8, gridBagConstraints);

        xTextFieldPROV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xTextFieldPROV.setMinimumSize(new java.awt.Dimension(150, 30));
        xTextFieldPROV.setPreferredSize(new java.awt.Dimension(180, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel6.add(xTextFieldPROV, gridBagConstraints);

        PanelCenter.add(panel6);

        panel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel7.setLayout(new java.awt.GridBagLayout());

        jLabelx9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelx9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelx9.setText("Telefono:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        panel7.add(jLabelx9, gridBagConstraints);

        xTextFieldTEL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xTextFieldTEL.setMinimumSize(new java.awt.Dimension(150, 30));
        xTextFieldTEL.setPreferredSize(new java.awt.Dimension(180, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panel7.add(xTextFieldTEL, gridBagConstraints);

        PanelCenter.add(panel7);

        MainPanel.add(PanelCenter, java.awt.BorderLayout.CENTER);

        PanelSouth.setBackground(new java.awt.Color(255, 255, 255));

        xBotonACEPTAR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xBotonACEPTAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok.png"))); // NOI18N
        xBotonACEPTAR.setText("Aceptar");
        xBotonACEPTAR.setMaximumSize(new java.awt.Dimension(80, 30));
        xBotonACEPTAR.setMinimumSize(new java.awt.Dimension(80, 30));
        xBotonACEPTAR.setPreferredSize(new java.awt.Dimension(180, 50));
        PanelSouth.add(xBotonACEPTAR);

        MainPanel.add(PanelSouth, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void editarVentana(String s) {
        this.setTitle(s+" Proveedor");
        this.xLabelTITULO.setText(s+" Proveedor");
        this.xBotonACEPTAR.setText(s);
        this.setLocationRelativeTo(null);
    }
    public void showError(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
    }

    public void showInfo(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "INFO",
                JOptionPane.INFORMATION_MESSAGE);
    }

    public JButton getxBotonACEPTAR() {
        return xBotonACEPTAR;
    }

    public JLabel getxLabelTITULO() {
        return xLabelTITULO;
    }

    public JTextField getxTextFieldCIF() {
        return xTextFieldCIF;
    }

    public JTextField getxTextFieldCP() {
        return xTextFieldCP;
    }

    public JTextField getxTextFieldDIR() {
        return xTextFieldDIR;
    }

    public JTextField getxTextFieldNOMBRE() {
        return xTextFieldNOMBRE;
    }

    public JTextField getxTextFieldPOB() {
        return xTextFieldPOB;
    }

    public JTextField getxTextFieldPROV() {
        return xTextFieldPROV;
    }

    public JTextField getxTextFieldTEL() {
        return xTextFieldTEL;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel PanelSouth;
    private javax.swing.JLabel jLabelx2;
    private javax.swing.JLabel jLabelx3;
    private javax.swing.JLabel jLabelx5;
    private javax.swing.JLabel jLabelx6;
    private javax.swing.JLabel jLabelx7;
    private javax.swing.JLabel jLabelx8;
    private javax.swing.JLabel jLabelx9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JPanel panel6;
    private javax.swing.JPanel panel7;
    private javax.swing.JButton xBotonACEPTAR;
    private javax.swing.JLabel xLabelTITULO;
    private javax.swing.JTextField xTextFieldCIF;
    private javax.swing.JTextField xTextFieldCP;
    private javax.swing.JTextField xTextFieldDIR;
    private javax.swing.JTextField xTextFieldNOMBRE;
    private javax.swing.JTextField xTextFieldPOB;
    private javax.swing.JTextField xTextFieldPROV;
    private javax.swing.JTextField xTextFieldTEL;
    // End of variables declaration//GEN-END:variables
}
