package View;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author lliurex
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        try {
            this.setIconImage(new ImageIcon(System.getProperty("user.dir") + "\\src\\images\\app-icon.png").getImage());
        } catch (Exception e) {
        }
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public JButton getxBotonCONECTAR() {
        return xBotonCONECTAR;
    }

    public JLabel getxLabelESTADO() {
        return xLabelESTADO;
    }

    public JButton getxBotonCONFIG() {
        return xBotonCONFIG;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlabelTitle = new javax.swing.JLabel();
        PanelCenter = new javax.swing.JPanel();
        PanelConexion = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        xBotonCONFIG = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        xLabelESTADO = new javax.swing.JLabel();
        xBotonCONECTAR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PanelUsername = new javax.swing.JPanel();
        jLabelUsername = new javax.swing.JLabel();
        xTextFieldEMPLEADO = new javax.swing.JTextField();
        PanelPassword = new javax.swing.JPanel();
        jLabelPassword = new javax.swing.JLabel();
        xTextFieldPASSWORD = new javax.swing.JPasswordField();
        PanelSouth = new javax.swing.JPanel();
        xBotonENTRAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1, 45));

        jlabelTitle.setBackground(new java.awt.Color(204, 255, 255));
        jlabelTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelTitle.setText("Login");
        jlabelTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlabelTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jlabelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlabelTitle.setMaximumSize(new java.awt.Dimension(70, 30));
        jlabelTitle.setMinimumSize(new java.awt.Dimension(70, 30));
        jlabelTitle.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jlabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jlabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MainPanel.add(jPanel1, java.awt.BorderLayout.NORTH);

        PanelCenter.setLayout(new java.awt.BorderLayout());

        PanelConexion.setBackground(new java.awt.Color(255, 255, 255));
        PanelConexion.setLayout(new java.awt.GridLayout(1, 0));

        xBotonCONFIG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        xBotonCONFIG.setText("Cofigurar Conexión (json)");
        jPanel3.add(xBotonCONFIG);

        PanelConexion.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        xLabelESTADO.setForeground(new java.awt.Color(102, 102, 102));
        xLabelESTADO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabelESTADO.setText("Desconectado");
        jPanel4.add(xLabelESTADO);

        xBotonCONECTAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xBotonCONECTAR.setText("Conectar");
        jPanel4.add(xBotonCONECTAR);

        PanelConexion.add(jPanel4);

        PanelCenter.add(PanelConexion, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        PanelUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelUsername.setLayout(new java.awt.GridBagLayout());

        jLabelUsername.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsername.setText("Empleado:  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        PanelUsername.add(jLabelUsername, gridBagConstraints);

        xTextFieldEMPLEADO.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xTextFieldEMPLEADO.setEnabled(false);
        xTextFieldEMPLEADO.setMinimumSize(new java.awt.Dimension(150, 30));
        xTextFieldEMPLEADO.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        PanelUsername.add(xTextFieldEMPLEADO, gridBagConstraints);

        jPanel2.add(PanelUsername);

        PanelPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelPassword.setLayout(new java.awt.GridBagLayout());

        jLabelPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPassword.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 19);
        PanelPassword.add(jLabelPassword, gridBagConstraints);

        xTextFieldPASSWORD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xTextFieldPASSWORD.setEnabled(false);
        xTextFieldPASSWORD.setMinimumSize(new java.awt.Dimension(150, 30));
        xTextFieldPASSWORD.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        PanelPassword.add(xTextFieldPASSWORD, gridBagConstraints);

        jPanel2.add(PanelPassword);

        PanelCenter.add(jPanel2, java.awt.BorderLayout.CENTER);

        MainPanel.add(PanelCenter, java.awt.BorderLayout.CENTER);

        xBotonENTRAR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xBotonENTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        xBotonENTRAR.setText("Entrar");
        xBotonENTRAR.setEnabled(false);
        xBotonENTRAR.setMaximumSize(new java.awt.Dimension(80, 30));
        xBotonENTRAR.setMinimumSize(new java.awt.Dimension(80, 30));
        xBotonENTRAR.setPreferredSize(new java.awt.Dimension(180, 50));
        PanelSouth.add(xBotonENTRAR);

        MainPanel.add(PanelSouth, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getxBotonENTRAR() {
        return xBotonENTRAR;
    }

    public JTextField getxTextFieldEMPLEADO() {
        return xTextFieldEMPLEADO;
    }

    public JPasswordField getxTextFieldPASSWORD() {
        return xTextFieldPASSWORD;
    }
    public void showError(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
    }

    public void showInfo(String msg) {
        JOptionPane.showMessageDialog(
                null,
                msg,
                "INFO",
                JOptionPane.INFORMATION_MESSAGE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel PanelConexion;
    private javax.swing.JPanel PanelPassword;
    private javax.swing.JPanel PanelSouth;
    private javax.swing.JPanel PanelUsername;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlabelTitle;
    private javax.swing.JButton xBotonCONECTAR;
    private javax.swing.JButton xBotonCONFIG;
    private javax.swing.JButton xBotonENTRAR;
    private javax.swing.JLabel xLabelESTADO;
    private javax.swing.JTextField xTextFieldEMPLEADO;
    private javax.swing.JPasswordField xTextFieldPASSWORD;
    // End of variables declaration//GEN-END:variables
}
