/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author god
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        try {
            this.setIconImage(new ImageIcon(System.getProperty("user.dir") + "\\src\\images\\app-icon.png").getImage());
        } catch (Exception e) {
        }
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public JLabel getxLabelUsuario() {
        return xLabelUsuario;
    }

    public JButton getxBotonBUSCAR() {
        return xBotonPROOVEDOR;
    }

    public JButton getxBotonCREDITOS() {
        return xBotonCREDITOS;
    }

    public JButton getxBotonCOMPRAS() {
        return xBotonCOMPRAS;
    }

    public JButton getxBotonPROOVEDOR() {
        return xBotonPROOVEDOR;
    }

    public JButton getxBotonLOGOUT() {
        return xBotonLOGOUT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlabelTitle = new javax.swing.JLabel();
        PanelCenter = new javax.swing.JPanel();
        center = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        xBotonCOMPRAS = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        xBotonPROOVEDOR = new javax.swing.JButton();
        Panel5 = new javax.swing.JPanel();
        xBotonCREDITOS = new javax.swing.JButton();
        PanelConexion = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        xLabelUsuario = new javax.swing.JLabel();
        xBotonLOGOUT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1, 45));

        jlabelTitle.setBackground(new java.awt.Color(204, 255, 255));
        jlabelTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelTitle.setText("Menu Principal");
        jlabelTitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jlabelTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jlabelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlabelTitle.setMaximumSize(new java.awt.Dimension(200, 30));
        jlabelTitle.setMinimumSize(new java.awt.Dimension(200, 30));
        jlabelTitle.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jlabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jlabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MainPanel.add(jPanel1, java.awt.BorderLayout.NORTH);

        PanelCenter.setLayout(new java.awt.BorderLayout());

        center.setLayout(new java.awt.GridLayout(3, 1));

        Panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel2.setLayout(new java.awt.GridBagLayout());

        xBotonCOMPRAS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        xBotonCOMPRAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compras.png"))); // NOI18N
        xBotonCOMPRAS.setText("Compras");
        xBotonCOMPRAS.setMinimumSize(new java.awt.Dimension(300, 50));
        xBotonCOMPRAS.setPreferredSize(new java.awt.Dimension(300, 50));
        Panel2.add(xBotonCOMPRAS, new java.awt.GridBagConstraints());

        center.add(Panel2);

        Panel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel3.setLayout(new java.awt.GridBagLayout());

        xBotonPROOVEDOR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        xBotonPROOVEDOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proveedores.png"))); // NOI18N
        xBotonPROOVEDOR.setText("Proveedores");
        xBotonPROOVEDOR.setMinimumSize(new java.awt.Dimension(300, 50));
        xBotonPROOVEDOR.setPreferredSize(new java.awt.Dimension(300, 50));
        Panel3.add(xBotonPROOVEDOR, new java.awt.GridBagConstraints());

        center.add(Panel3);

        Panel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Panel5.setLayout(new java.awt.GridBagLayout());

        xBotonCREDITOS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        xBotonCREDITOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/creditos.png"))); // NOI18N
        xBotonCREDITOS.setText("Creditos");
        xBotonCREDITOS.setMinimumSize(new java.awt.Dimension(300, 50));
        xBotonCREDITOS.setPreferredSize(new java.awt.Dimension(300, 50));
        Panel5.add(xBotonCREDITOS, new java.awt.GridBagConstraints());

        center.add(Panel5);

        PanelCenter.add(center, java.awt.BorderLayout.CENTER);

        PanelConexion.setBackground(new java.awt.Color(255, 255, 255));
        PanelConexion.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Empleado:     ");
        jPanel2.add(jLabel1);

        PanelConexion.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        xLabelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        xLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabelUsuario.setText("_usuario_");
        jPanel4.add(xLabelUsuario);

        xBotonLOGOUT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xBotonLOGOUT.setText("Log out");
        jPanel4.add(xBotonLOGOUT);

        PanelConexion.add(jPanel4);

        PanelCenter.add(PanelConexion, java.awt.BorderLayout.NORTH);

        MainPanel.add(PanelCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel5;
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel PanelConexion;
    private javax.swing.JPanel center;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlabelTitle;
    private javax.swing.JButton xBotonCOMPRAS;
    private javax.swing.JButton xBotonCREDITOS;
    private javax.swing.JButton xBotonLOGOUT;
    private javax.swing.JButton xBotonPROOVEDOR;
    private javax.swing.JLabel xLabelUsuario;
    // End of variables declaration//GEN-END:variables
}
